orientation_covariance: [0.01,  0.0,   0.0,
                        0.0,   0.01,  0.0,
                        0.0,   0.0,   0.01]
angular_velocity_covariance: [0.01,  0.0,   0.0,
                     0.0,   0.01,  0.0,
                     0.0,   0.0,   0.01]
linear_acceleration_covariance: [0.01,  0.0,   0.0,
                     0.0,   0.01,  0.0,
                     0.0,   0.0,   0.01]
magnetic_covariance: [0.01,  0.0,   0.0,
                     0.0,   0.01,  0.0,
                     0.0,   0.0,   0.01]
